# Generated by Django 3.0 on 2019-12-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdata',
            name='framework',
        ),
        migrations.AddField(
            model_name='appdata',
            name='build',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='appdata',
            name='env',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
        migrations.AddField(
            model_name='appdata',
            name='version',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
