# Generated by Django 3.0 on 2019-12-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='logdata',
        ),
    ]
